### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by Alexvrse** [bstuff/haier-ac-remote#13]
I modified the code by adding an error handler:

diff -rc ./old/haier-ac-remote/dist/HaierAC.js ./new/haier-ac-remote/dist/HaierAC.js
*** ./old/haier-ac-remote/dist/HaierAC.js<----->2020-06-20 23:11:38.022521341 +0300
--- ./new/haier-ac-remote/dist/HaierAC.js<----->2020-06-21 21:54:45.319943115 +0300
***************
*** 96,101 ****
--- 96,106 ----
              }
              logError('Connection closed>>>');
          });
+         this._client.on("error", (err) => {
+             //this._connect();
+             logError('Connection error>>>');
+             logError(err.stack);
+         });
          this.state$.subscribe(logState);
      }
      _connect() {

Now, after entering any command after starting the example, the program does not crash, but produces the following error:

haier-ac-remote@0.1.2 run:example /home/pi/test/haier-ac-remote/packages/haier-ac-remote
> DEBUG=* node ./dist/examples/index.js

  haier-ac:state {
  haier-ac:state   currentTemperature: 21,
  haier-ac:state   targetTemperature: 21,
  haier-ac:state   fanSpeed: 2,
  haier-ac:state   mode: 3,
  haier-ac:state   health: false,
  haier-ac:state   limits: 0,
  haier-ac:state   power: false
  haier-ac:state } +0ms
  haier-ac:sent 00000000: 00 00 27 14 00 00 00 00 00 00 00 00 00 00 00 00    ..'.............
  haier-ac:sent 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
  haier-ac:sent 00000020: 00 00 00 00 00 00 00 00 30 34 46 41 38 33 32 41    ........04FA832A
  haier-ac:sent 00000030: 35 38 34 38 00 00 00 00 00 00 00 00 00 00 00 00    5848............
  haier-ac:sent 00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0d    ................
  haier-ac:sent 00000050: ff ff 0a 00 00 00 00 00 00 01 4d 02 5a             ..........M.Z
  haier-ac:sent  +0ms
  haier-ac:error Connection error>>> +0ms
  haier-ac:error Error: read ECONNRESET
  haier-ac:error     at TCP.onStreamRead (internal/stream_base_commons.js:205:27) +2ms
  haier-ac:error Connection closed>>> +1ms
  haier-ac:error Connection closed>>> +22s

**Comment by Skull09rus** [comment]
same thing Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27) and HB restart after (

**Comment by bstuff** [comment]
Thanks for reporting this 🙏 The project just went through a big modernization: updated toolchain, RxJS 7, a socket error handler, and more resilient reconnect handling. These older connection-drop reports predate those fixes and are hard to reproduce now, so I am closing this as stale during a cleanup. If you still hit it on the latest version, please open a fresh issue with details — happy to dig in. Thanks for being part of the project! 🚀
