### ISSUE TITLE
Error: read ECONNRESET - Hailer Flexis Plus with built-in WiFi

### ISSUE THREAD

**Issue by kost** [bstuff/haier-ac-remote#19]
Hello!

Just tried your basic example on Haier Flexis Plus and got this error:
```
$ node dist/examples/index.js
events.js:193
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1031:13)
    at TCP.onread (net.js:619:25)
```

Snifing communication between the code and the AC, it looks like the example sent some bytes to the AC, but the AC answered with closing TCP connection without any response.

Double checked the IP and MAC in the dist/examples/index.js

Seems like similar problem that @stravinci have.

**Comment by bstuff** [comment]
Thanks for reporting this 🙏 The project just went through a big modernization: updated toolchain, RxJS 7, a socket error handler, and more resilient reconnect handling. These older connection-drop reports predate those fixes and are hard to reproduce now, so I am closing this as stale during a cleanup. If you still hit it on the latest version, please open a fresh issue with details — happy to dig in. Thanks for being part of the project! 🚀
