### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by agafirss** [bstuff/haier-ac-remote#3]
Everything worked fine, but recently when turning on, an error began to appear in the logs 

```
> [5/13/2020, 10:06:29 AM] Error: read ECONNRESET
>     at TCP.onStreamRead (internal/stream_base_commons.js:200:27)
> [5/13/2020, 10:06:32 AM] [1] [Error [TimeoutError]: Timeout has occurred] {
>   message: 'Timeout has occurred',
>   name: 'TimeoutError'
> }
```
changing ip address, deleting and setting the air conditioner again did not help
control via a native application SmartAir2 works.

**Comment by exotsk** [comment]
i have the same.
Homebridge is HOOBS on docker

`25.05.2020, 22:31:26 Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
25.05.2020, 22:31:26 Got SIGTERM, shutting down Bridge...
25.05.2020, 22:31:29 [Кондиционер] [Error [TimeoutError]: Timeout has occurred] {
  message: 'Timeout has occurred',
  name: 'TimeoutError'
}`

**Comment by bstuff** [comment]
This is an issue in haier-ac-remote lib.
There must be a mechanism to check if connection is alive. Feel free to make a pull-request!

**Comment by agafirss** [comment]
Not work
the same problem 
[6/19/2020, 10:19:09 AM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:200:27)

**Comment by cloudwalker87** [comment]
I have the same thing. I initially thought the issue was that my host (ubuntu 18.4) used IPv6 so disabled this, but I can't get it work

[6/19/2020, 9:34:29 PM] Homebridge is running on port 51289.
[6/19/2020, 9:34:52 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
[6/19/2020, 9:34:52 PM] Got SIGTERM, shutting down Homebridge...
[6/19/2020, 9:34:55 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

**Comment by d10d** [comment]
Hi @bstuff , unfortunately still same problem. Latest homebridge + latest version of your plugin. Please help! :)

Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)

**Comment by xnakk** [comment]
Was this issue ever fixed ? I'm getting this error when trying to turn on the AC

[3/19/2021, 8:14:06 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[3/19/2021, 8:14:06 PM] Got SIGTERM, shutting down Homebridge...
[3/19/2021, 8:14:09 PM] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[3/19/2021, 8:14:11 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[3/19/2021, 8:14:16 PM] [HB Supervisor] Restarting Homebridge...

**Comment by fayewave** [comment]
The devices appear in HomeKit but when I interact with them they immediately undo anything I've done, the error ECONNRESET appears in the log, then HomeBridge restarts itself.

**Comment by Lennys26** [comment]
It does not look like this was ever resolved. I have retested on separate installs, different Pi's, different model Pi's.

Does anyone have a workaround (or another working plugin)?

```
[22/12/2021, 13:26:37] Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
[22/12/2021, 13:26:37] Got SIGTERM, shutting down Homebridge...
[22/12/2021, 13:26:37] [Homebridge UI] [HapClient] [192.168.1.62:51974 (0E:74:17:9A:4D:6A)] Failed to set value for Office Conditioner.
[22/12/2021, 13:26:40] Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20)
[22/12/2021, 13:26:42] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[22/12/2021, 13:26:42] [Homebridge UI] [HapClient] [192.168.1.62:51974 (0E:74:17:9A:4D:6A)] Failed to set value for Bedroom Conditioner.
```
